### ISSUE TITLE
Merge pdf fails in particular case

### ISSUE THREAD

**Issue by jkb016** [itext/itext7#1]
Merge pdf is working for most cases. I have one case where there are 2 documents. One has rotation set to 270 and other document is in landscape. I tried merging 2 docs and it fails. The code works fine for any one file , but not for both .
Stacktrace : 
java.lang.NullPointerException
	at com.itextpdf.kernel.pdf.PdfDocument.copyPagesTo(PdfDocument.java:990)
	at com.itextpdf.kernel.pdf.PdfDocument.copyPagesTo(PdfDocument.java:1028)
	at com.itextpdf.kernel.pdf.PdfDocument.copyPagesTo(PdfDocument.java:1013)
	at com.itextpdf.kernel.utils.PdfMerger.merge(PdfMerger.java:132)
	at com.itextpdf.kernel.utils.PdfMerger.merge(PdfMerger.java:112)
	at com.netkiller.servlet.MergePdfServlet.mergeDocs(MergePdfServlet.java:383)

code : 
```
		for (String fileId : driveFileMap.keySet()) {
			byte[] driveFileBytes1 = byteMap.get(fileId);
			driveFile = driveFileMap.get(fileId);
			PdfDocument sourcePdf = new PdfDocument(new PdfReader(new ByteArrayInputStream(driveFileBytes1)));
			merger.merge(sourcePdf, 1, sourcePdf.getNumberOfPages());
			sourcePdf.close();
		}
```

**Comment by amedee** [comment]
Hello, for Community Support please ask your question on StackOverflow: http://stackoverflow.com. If you are a customer with a support contract, you have access to our JIRA. For more information, please see http://itextpdf.com/support
